### ISSUE TITLE
Missing endpoints

### ISSUE THREAD

**Issue by prozenn** [polygon-io/client-php#12]
Hi!

Some endpoints are missing in this package, e.g:
- Stock API (Last Trade for a Symbol v2) /v2/last/trade/{stocksTicker}
- Stock API (Last Quote for a Symbol v2) /v2/last/nbbo/{stocksTicker}
- Forex API (Snapshot - Ticker) /v2/snapshot/locale/global/markets/forex/tickers/{ticker}

Can you add it?

**Comment by ersin-demirtas** [comment]
Included in new v1.2.0 release
