### ISSUE TITLE
HistoricTradesV2.php incorrect array key when parsing response

### ISSUE THREAD

**Issue by ThatGuyAstro** [polygon-io/client-php#14]
### **Issue**

- _"mapper" function is trying to resolve response-data via the "ticks" array key, this throws an error. (@ lines 53 and 58)_

### **Solution**

- _Change the resolving array key to "results"_

Not sure what your guys pull-request protocol is... but this is a simple fix so you can prob. just throw into the pipeline of low hanging fruit.

Thanks!

**Comment by ersin-demirtas** [comment]
The tests are bad, I am going to work on all the issues this weekend. I am going to push a fix for this in couple of minutes.

**Comment by ersin-demirtas** [comment]
@ThatGuyAstro thank you for contributing.
