### ISSUE TITLE
Laravel installation

### ISSUE THREAD

**Issue by darkcavalry** [polygon-io/client-php#16]
Hello,

composer gives "Install of polygon-io/api failed" while installation on Laravel. When I try your laravel package, its also gives "Could not find a matching version of package ersindemirtas/polygonio-laravel. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev)." error.

Laravel verison ^8.75

Regards.

**Comment by matichenor** [comment]
Hi @darkcavalry , the laravel package you referenced is a community effort built by our users.  We don't actively maintain that package.  I suggest you follow up at https://github.com/ersin-demirtas/polygonio-laravel .

We are planning to expand our library of officially supported integrations in the near future, so I'll keep a laravel package in mind :)
