### ISSUE TITLE
Could not read configuration file '/etc/resolv.conf' 

### ISSUE THREAD

**Issue by MixMe** [polygon-io/client-php#21]
Hi i got this error:

Amp\Dns\ConfigException

Could not read configuration file '/etc/resolv.conf' (2) file_get_contents(): open_basedir restriction in effect. File(/etc/resolv.conf) is not within the allowed path(s): (/app/:/usr/lib/php/:/tmp/)

i use latest SDK, i am on Mac running docker

**Comment by justinpolygon** [comment]
Hey @MixMe, I suspect this is related to the docker image you're using since we don't call `etc/resolv.conf` anywhere. What docker image are you using so I can try and reproduce the issue?
