### ISSUE TITLE
'PolygonIO' has no effect

### ISSUE THREAD

**Issue by kevinrhanson** [polygon-io/client-php#5]
Installed via composer and getting the following warning:

Warning: The use statement with non-compound name 'PolygonIO' has no effect in /home/ ... .php on line 8
Fatal error: Uncaught Error: Class 'PolygonIO' not found in /home/ ....

**Comment by SourceCode** [comment]
Yes I am noticing the same thing, the first warning sign is the requirements for guzzle 6.

**Comment by ersin-demirtas** [comment]
@SourceCode the guzzle issue has been resolved and will be released soon. 

https://github.com/polygon-io/client-php/issues/8
