### ISSUE TITLE
Need to update Guzzle version 

### ISSUE THREAD

**Issue by andrii-cherkavskyi** [polygon-io/client-php#8]
Hello!
Seems like you're using outdated ```guzzlehttp/guzzle``` version, so I can't install your package since I'm using packages which requires guzzle 7.x.

Hope you'll add support for version 7.x

**Comment by dog5tar** [comment]
Same issue.

**Comment by ersin-demirtas** [comment]
I have added Guzzle 7.2 to develop branch and will be released soon.
